id=webhook-signature-generator
name=Webhook Signature Generator
version=${project.version}
description=${project.description}
class=io.gravitee.policy.webhook_signature_generator.WebhookSignatureGeneratorPolicy
type=policy
category=security
icon=webhook-logo.svg
documentation=README.adoc
schema=schema-form.json
proxy=RESPONSE
message=MESSAGE_RESPONSE
